module.exports = {
  env: {
    browser: true,
    es2021: true,
    node: true
  },
  extends: "eslint:recommended",
  parserOptions: {
    ecmaVersion: 12,
    sourceType: "module"
  },
  rules: {
    "indent": [ "error", 2 ],
    "linebreak-style": [ "error", "unix" ],
    "quotes": [ "error", "double" ],
    "semi": [ "error", "always" ],
    "no-extra-parens": [ "error", "all" ],
    "no-unreachable-loop": 2,
    "no-constant-condition": 0,
    "no-else-return": 2,
    "no-extra-bind": 2,
    "no-multi-spaces": 2,
    "no-useless-return": 2,
    "yoda": 2,
    "no-undef-init": 2,
    "prefer-const": 2,
    "prefer-template": 2,
    "prefer-arrow-callback": 2,
    "no-var": 2,
    "no-useless-constructor": 2,
    "spaced-comment": 2,
    "switch-colon-spacing": 2,
    "quote-props": [ "error", "consistent-as-needed" ],
    "prefer-exponentiation-operator": 2,
    "no-unneeded-ternary": 2,
    "no-lonely-if": 2,
    "key-spacing": 2,
    "func-call-spacing": 2,
    "keyword-spacing": 2,
    "comma-dangle": 2,
    "brace-style": 2,
    "array-bracket-spacing": [ "error", "always", { objectsInArrays: false, arraysInArrays: false }],
    "camelcase": 2,
    "block-spacing": 2,
    "computed-property-spacing": 2,
    "dot-location": [ "error", "property" ],
    "dot-notation": 2,
    "no-implicit-coercion": 2,
    "prefer-rest-params": 2,
    "space-before-function-paren": [ "error", "never" ],
    "curly": [ "error", "multi-line" ],
    "function-call-argument-newline": [ "error", "never" ],
    "space-in-parens": 2,
    "space-before-blocks": 2,
    "no-trailing-spaces": 2
  }
};
